### ISSUE TITLE
OL9 breaks text rendering

### ISSUE THREAD

**Issue by gberaudo** [geoblocks/print#8]

**Comment by ismailsunni** [comment]
Could you give more information about the breaking text rendering? Since you are busy this week, may be I can try to check it also.

**Comment by gberaudo** [comment]
Hi @ismailsunni, when using OL9 I did not see the texts anymore.
Simply start the demo and you will see that they do not appear.

OL9 changed the way decluttering is implemented.

**Comment by fredj** [comment]
See #9
